
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 02 16:43:04 CDT 2021
//----------------------------------------------------

package mx.jcc.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EOL = 8;
  public static final int KEYWORD_NONTERM = 4;
  public static final int FLECHA = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int TERMINAL = 3;
  public static final int COMMA = 6;
  public static final int KEYWORD_TERMINAL = 5;
  public static final int NONTERM = 2;
}

