
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 01 21:21:35 CDT 2021
//----------------------------------------------------

package mx.jcc.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMMA = 4;
  public static final int TERMINAL = 3;
  public static final int EOL = 5;
  public static final int error = 1;
  public static final int NONTERM = 2;
  public static final int EOF = 0;
}

