
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 02 20:16:02 CDT 2021
//----------------------------------------------------

package mx.jcc.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLECHA = 6;
  public static final int COMMA = 5;
  public static final int VAR = 2;
  public static final int EOL = 7;
  public static final int error = 1;
  public static final int KEYWORD_TERMINAL = 4;
  public static final int KEYWORD_NONTERM = 3;
  public static final int EOF = 0;
}

